name: Package and Deploy to GitHub Pages
on: [push]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    package:
        runs-on: ubuntu-latest
        container:
            image: wonderlandengine/editor:edge
        steps:
            - uses: actions/checkout@v2
            - name: Package
              run: |
                  apt install -y zip
                  mkdir public
                  for project in * ; do
                    if [ ! -d "$project" ]; then continue; fi
                    if [ "$project" = ".github" ]; then continue; fi
                    if [ "$project" = "public" ]; then continue; fi

                    echo "Zipping $project"
                    zip -r ./public/$project.zip $project

                    echo "Building $project"
                    for projectFile in $project/*.wlp ; do
                      /usr/local/bin/entrypoint.sh WonderlandEditor --credentials "$WLE_CREDENTIALS" --windowless --package --project ./$projectFile --output ./public/
                    done
                    mv public/index.html public/$project.html
                  done
              env:
                  WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
            - name: Gzip
              run: gzip -k public/**/*.*
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./public

    deploy-pages:
        needs: package
        runs-on: ubuntu-latest
        if: ${{ format('refs/heads/{0}', ) == github.ref }}
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2
